
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: AnalyzeLots.py

    - uses: actions/upload-artifact@v2
      with:
        name: WindowsExecutable
        path: dist/AnalyzeLots/windows
