
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
    paths: 
      -  '**.py'
  pull_request:
    branches: [ main ]
    paths: 
      -  '**.py'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v4
      with:
        name: AnalyzeLots.exe
        path: dist/windows/AnalyzeLots/AnalyzeLots.exe
